"""
NIFTY 200 universe — standard NSE trading symbols as used by Dhan/Tradehull.
Update this list whenever index constituents change (quarterly rebalance).
"""

NIFTY_200 = [
    # ── NIFTY 50 ──────────────────────────────────────────────────────────────
    "ADANIPORTS", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE",
    "BAJAJFINSV", "BPCL", "BHARTIARTL", "BRITANNIA", "CIPLA",
    "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT", "GRASIM",
    "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO",
    "HINDUNILVR", "ICICIBANK", "INFY", "ITC", "INDUSINDBK",
    "JSWSTEEL", "KOTAKBANK", "LT", "M&M", "MARUTI",
    "NTPC", "NESTLEIND", "ONGC", "POWERGRID", "RELIANCE",
    "SBIN", "SUNPHARMA", "TATACONSUM", "TATASTEEL", "TECHM",
    "TITAN", "TRENT", "ULTRACEMCO", "WIPRO", "ZOMATO",
    "ADANIENT", "ETERNAL", "JIOFIN", "SHRIRAMFIN", "BEL",

    # ── NIFTY NEXT 50 ─────────────────────────────────────────────────────────
    "ABB", "AMBUJACEM", "APOLLOHOSP", "BAJAJHLDNG", "BANKBARODA",
    "BHEL", "CGPOWER", "CUMMINSIND", "DLF", "GAIL",
    "GODREJCP", "HAL", "HAVELLS", "INDHOTEL", "JINDALSTEL",
    "JSWENERGY", "LODHA", "LTIM", "MOTHERSON", "MUTHOOTFIN",
    "NHPC", "NMDC", "NAUKRI", "PFC", "PIDILITIND",
    "PNB", "RECLTD", "SBILIFE", "SIEMENS", "SRF",
    "TATAPOWER", "TORNTPHARM", "TVSMOTOR", "UNIONBANK", "VBL",
    "VEDL", "ADANIGREEN", "ADANIENSOL", "IRFC", "IRCTC",
    "MAXHEALTH", "POLICYBZR", "DMART", "HDFCAMC", "SOLARINDS",
    "KPITTECH", "PERSISTENT", "OFSS", "MPHASIS", "COFORGE",

    # ── NIFTY MIDCAP 100 (additional) ─────────────────────────────────────────
    "ACC", "APLAPOLLO", "AUBANK", "BANDHANBNK", "BERGEPAINT",
    "BOSCHLTD", "CANBK", "CHOLAFIN", "COROMANDEL", "DABUR",
    "DEEPAKNTR", "ESCORTS", "EXIDEIND", "FEDERALBNK", "GLENMARK",
    "GODREJPROP", "HINDCOPPER", "IDFCFIRSTB", "INDUSTOWER", "IOC",
    "JKCEMENT", "JUBLFOOD", "LALPATHLAB", "LUPIN", "MANAPPURAM",
    "MCX", "MFSL", "PAGEIND", "PETRONET", "PIIND",
    "POLYCAB", "RBLBANK", "SAIL", "SONACOMS", "TIINDIA",
    "TORNTPOWER", "UBL", "VOLTAS", "ZYDUSLIFE", "ASTRAL",
    "BALKRISIND", "BATAINDIA", "CROMPTON", "DALBHARAT", "GNFC",
    "JSWINFRA", "KALYANKJIL", "KEI", "LICI", "LTTS",
    "NYKAA", "OBEROIRLTY", "POONAWALLA", "PRESTIGE", "SUPREMEIND",
    "TATAELXSI", "TATACHEM", "AARTIIND", "ABCAPITAL", "ALKEM",
    "AUROPHARMA", "BIOCON", "BLUESTARCO", "CAMS", "CANFINHOME",
    "CDSL", "CHOLAHLDNG", "CREDITACC", "DCBBANK", "EIDPARRY",
    "EMAMILTD", "FINPIPE", "FLUOROCHEM", "FORTIS", "GICRE",
    "GLAXO", "HBLPOWER", "HUDCO", "INDIANB", "INDIAMART",
    "IOLCP", "IPCALAB", "JBCHEPHARM", "JYOTHYLAB", "KANSAINER",
    "KAYNES", "LICHSGFIN", "MAHLIFE", "MEDANTA", "METROPOLIS",
    "MGL", "NAVINFLUOR", "NIACL", "OLECTRA", "PATANJALI",
    "PCBL", "PFIZER", "RITES", "RRKABEL", "SCHAEFFLER",
    "SJVN", "SKFINDIA", "SYNGENE", "THERMAX", "TRIDENT",
]
