NIFTY_100 = [
    # NIFTY 50
    "RELIANCE", "TCS", "HDFCBANK", "BHARTIARTL", "ICICIBANK",
    "INFY", "SBIN", "HINDUNILVR", "ITC", "LT",
    "KOTAKBANK", "AXISBANK", "BAJFINANCE", "MARUTI", "HCLTECH",
    "SUNPHARMA", "TITAN", "WIPRO", "ULTRACEMCO", "ASIANPAINT",
    "BAJAJFINSV", "NTPC", "POWERGRID", "TATAMOTORS", "ADANIPORTS",
    "ONGC", "COALINDIA", "TATASTEEL", "JSWSTEEL", "INDUSINDBK",
    "GRASIM", "DRREDDY", "TECHM", "CIPLA", "DIVISLAB",
    "ADANIENT", "BRITANNIA", "HINDALCO", "BAJAJ-AUTO", "HEROMOTOCO",
    "EICHERMOT", "TATACONSUM", "NESTLEIND", "BPCL", "IOC",
    "APOLLOHOSP", "HDFCLIFE", "SBILIFE", "M&M", "LTIM",

    # NIFTY NEXT 50
    "PIDILITIND", "DABUR", "MARICO", "SIEMENS", "HAVELLS",
    "BERGEPAINT", "GODREJCP", "MUTHOOTFIN", "CHOLAFIN", "MOTHERSON",
    "DLF", "NAUKRI", "ZOMATO", "POLYCAB", "TRENT",
    "DMART", "COLPAL", "TORNTPHARM", "AUROPHARMA", "LUPIN",
    "ALKEM", "IDFCFIRSTB", "FEDERALBNK", "BANDHANBNK", "CANBK",
    "PNB", "SAIL", "NMDC", "CONCOR", "GAIL",
    "PETRONET", "MFSL", "COFORGE", "PERSISTENT", "MPHASIS",
    "LTTS", "PIIND", "APLAPOLLO", "NAVINFLUOR", "SOLARINDS",
    "SKFINDIA", "TATACHEM", "JUBLFOOD", "PATANJALI", "ESCORTS",
    "JKCEMENT", "VEDL", "TATACOMM", "HFCL", "IRCTC",
]
